global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'atp_re'

scrape_configs:
  # ATP_Re API metrics
  - job_name: 'atp_api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Redis metrics (optional, requires redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
    scrape_interval: 10s

  # PostgreSQL metrics (optional, requires postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
    scrape_interval: 10s
