# .github/workflows/decompile.yml
name: Decompile Java classes & jars

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  decompile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java (for CFR)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Ensure decompile script exists and is executable
        run: |
          mkdir -p .github/scripts
          if [ ! -f .github/scripts/decompile-all.sh ]; then
            echo "Error: .github/scripts/decompile-all.sh not found in the repository. Please add the script to the decompile-workflow branch."
            exit 1
          fi
          chmod +x .github/scripts/decompile-all.sh

      - name: Run decompiler
        run: .github/scripts/decompile-all.sh

      - name: Commit decompiled sources to branch and open PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(decompiled): add automated decompiled sources"
          title: "Automated: Decompiled sources (CFR)"
          body: |
            This PR was automatically generated by the decompilation workflow.
            Decompilation was performed using CFR. Note: Decompiled code may be incomplete or not compile.
          branch: decompiled/sources
